wallet:
  file-path: /home/ubuntu/did-orchestrator-server/source/did-orchestrator-server/jars/Issuer/issuer.wallet
  password: omnioneopendid12!@

zkp-wallet:
  file-path:
  password: omnioneopendid12!@